// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // about: [{type: 'autogenerated', dirName: 'README'}],
  main: [{type: 'autogenerated', dirName: '筆記'}],
  // portfolio: [{type: 'autogenerated', dirName: 'Portfolio'}],
};

module.exports = sidebars;

